"""定义反编译 worker、文件预览和自动处理缓存的共享常量。"""

import os

READ_CHUNK_BYTES = 64 * 1024
MAX_PREVIEW_BYTES = 16 * 1024 * 1024
MAX_TARGET_PREVIEW_BYTES = 2 * 1024 * 1024
TARGET_PREVIEW_CONTEXT_LINES = 80
MAX_BINARY_PREVIEW_BYTES = 64 * 1024 * 1024
FORMATTER_WORKER_COUNT = max(2, min(8, os.cpu_count() or 4))
FORMATTER_PROGRESS_INTERVAL = 20
AUTO_MATCH_CHUNK_SIZE = 200
AUTO_PROCESS_CACHE_VERSION = 1
AUTO_PROCESS_CACHE_DIR_NAME = ".e0e1_cache"
AUTO_PROCESS_CACHE_FILE_NAME = "applet_processing_state.json"
LEGACY_PAGE_CACHE_FILE_NAME = "decompile_page_state.json"
AUTO_PROCESS_CACHE_LIMIT = 200
